version: "3.8"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis

    command: sh -c "npm install && npm start"

  db:
    container_name: db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/db/schemas/library-management.sql:/docker-entrypoint-initdb.d/library-management.sql
    ports:
      - "5432:5432"

  redis:
    container_name: ${REDIS_HOST}
    image: redis
    env_file:
      - .env
    expose:
      - ${REDIS_PORT}
    volumes:
      - "redis_data:/data"

volumes:
  redis_data:
  db_data: