version: "3.8"

services:
  app:
    image: node:latest
    working_dir: /app
    environment:
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: "library_managment"
      PGUSER: "postgres"
      PGPASSWORD: root
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: root
      POSTGRES_DB: "library_managment"
    ports:
      - "5432:5432"

  redis:
    container_name: ${REDIS_HOST}
    image: redis
    env_file:
      - .env
    expose:
      - ${REDIS_PORT}
    volumes:
      - "redis_data:/data"

volumes:
  redis_data:
  db_data: